version: "3.7"
services:
  app:
    container_name: "authAPI"
    image: img
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "8008:8008"
    depends_on:
      db1:
        condition: service_healthy

  db1:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d auth-api-db -U user"]
      interval: 5s
      timeout: 5s
      retries: 5